"""create core domain tables

Revision ID: a06f3f5966ec
Revises:
Create Date: 2026-09-09 12:42:35.536172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06f3f5966ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('MEMORY', 'CONCENTRATION_ATTENTION')", name='ck_games_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_games_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('PATIENT', 'CAREGIVER')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('caregivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("caregiver_type IN ('FAMILY', 'DOCTOR', 'PROFESSIONAL_CAREGIVER', 'OTHER')", name='ck_caregivers_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_caregivers_user_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('profile_photo_ref', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_patients_user_id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('STARTED', 'COMPLETED', 'ABANDONED')", name='ck_game_sessions_status'),
    sa.CheckConstraint('difficulty_level IN (1, 2, 3)', name='ck_game_sessions_difficulty_level'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_game_sessions_patient_started', 'game_sessions', ['patient_id', 'started_at'], unique=False)
    op.create_table('patient_caregivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'caregiver_id', name='uq_patient_caregivers_pair')
    )
    op.create_index('ix_patient_caregivers_primary_patient', 'patient_caregivers', ['patient_id'], unique=True, postgresql_where='is_primary = TRUE')
    op.create_table('performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('memory_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attention_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('games_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attention_score IS NULL OR (attention_score >= 0 AND attention_score <= 100)', name='ck_performance_metrics_attention_score'),
    sa.CheckConstraint('average_accuracy IS NULL OR (average_accuracy >= 0 AND average_accuracy <= 100)', name='ck_performance_metrics_accuracy'),
    sa.CheckConstraint('average_response_time_ms IS NULL OR average_response_time_ms >= 0', name='ck_performance_metrics_response_nonnegative'),
    sa.CheckConstraint('games_completed <= total_sessions', name='ck_performance_metrics_games_lte_sessions'),
    sa.CheckConstraint('games_completed >= 0', name='ck_performance_metrics_games_nonnegative'),
    sa.CheckConstraint('memory_score IS NULL OR (memory_score >= 0 AND memory_score <= 100)', name='ck_performance_metrics_memory_score'),
    sa.CheckConstraint('total_sessions >= 0', name='ck_performance_metrics_sessions_nonnegative'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'metric_date', name='uq_performance_metrics_patient_date')
    )
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reminder_type IN ('MEDICATION', 'APPOINTMENT', 'GAME', 'ACTIVITY', 'OTHER')", name='ck_reminders_type'),
    sa.CheckConstraint('(is_recurring = TRUE AND recurrence_rule IS NOT NULL) OR (is_recurring = FALSE AND recurrence_rule IS NULL)', name='ck_reminders_recurrence'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_patient_id', 'reminders', ['patient_id'], unique=False)
    op.create_table('game_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy IS NULL OR (accuracy >= 0 AND accuracy <= 100)', name='ck_game_results_accuracy'),
    sa.CheckConstraint('correct_answers IS NULL OR correct_answers >= 0', name='ck_game_results_correct_nonnegative'),
    sa.CheckConstraint('correct_answers IS NULL OR total_questions IS NULL OR correct_answers <= total_questions', name='ck_game_results_correct_lte_total'),
    sa.CheckConstraint('mistakes IS NULL OR mistakes >= 0', name='ck_game_results_mistakes_nonnegative'),
    sa.CheckConstraint('response_time_ms IS NULL OR response_time_ms >= 0', name='ck_game_results_response_nonnegative'),
    sa.CheckConstraint('score >= 0', name='ck_game_results_score_nonnegative'),
    sa.CheckConstraint('total_questions IS NULL OR total_questions > 0', name='ck_game_results_total_positive'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_game_results_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_results')
    op.drop_index('ix_reminders_patient_id', table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('performance_metrics')
    op.drop_index('ix_patient_caregivers_primary_patient', table_name='patient_caregivers', postgresql_where='is_primary = TRUE')
    op.drop_table('patient_caregivers')
    op.drop_index('ix_game_sessions_patient_started', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('patients')
    op.drop_table('caregivers')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
